export const WeatherIcons = {
  "01d": "/weather-application/icons/sunny.svg",
  "01n": "/weather-application/icons/night.svg",
  "02d": "/weather-application/icons/day.svg",
  "02n": "/weather-application/icons/cloudy-night.svg",
  "03d": "/weather-application/icons/cloudy.svg",
  "03n": "/weather-application/icons/cloudy.svg",
  "04d": "/weather-application/icons/perfect-day.svg",
  "04n": "/weather-application/icons/cloudy-night.svg",
  "09d": "/weather-application/icons/rain.svg",
  "09n": "/weather-application/icons/rain-night.svg",
  "10d": "/weather-application/icons/rain.svg",
  "10n": "/weather-application/icons/rain-night.svg",
  "11d": "/weather-application/icons/storm.svg",
  "11n": "/weather-application/icons/storm.svg",
};
